import AppKit
import SwiftUI

/// Loads the GitHub mark from `Resources/GithubMark.svg` (the user's own
/// downloaded copy of GitHub's official Invertocat asset) via macOS's
/// native `NSImage` SVG parser.
///
/// Why a bundled file rather than inlined SVG path data:
///   * The user supplied the asset themselves from GitHub's brand kit, so
///     the canonical copy stays in its own file — no source-tree mutation
///     of GitHub's mark, no risk of drifting from the official version.
///   * `Bundle.module` is generated by SwiftPM whenever the target has a
///     `resources:` declaration. The build script copies the resulting
///     `*.bundle` into the packaged `.app`, so this works in both
///     `swift run` and the produced application.
///
/// The image is created once and cached. We mark it as a template image so
/// SwiftUI's `.foregroundStyle` tints it the same way it tints SF Symbols.
enum GithubMarkImage {
    /// Cached single instance. NSImage's SVG parser is cheap but there's no
    /// reason to redo it per row.
    static let shared: NSImage? = makeImage()

    private static func makeImage() -> NSImage? {
        guard let url = Bundle.module.url(forResource: "GithubMark", withExtension: "svg"),
              let image = NSImage(contentsOf: url) else {
            return nil
        }
        // Template = monochrome silhouette honored by SwiftUI tint.
        image.isTemplate = true
        return image
    }
}

/// SwiftUI wrapper around the GitHub mark with a system-symbol fallback if
/// the SVG fails to load (resource missing from the .app, parser failure,
/// etc.). The fallback keeps the action button functional even if the
/// resource pipeline breaks.
struct GithubMarkView: View {
    var body: some View {
        if let image = GithubMarkImage.shared {
            Image(nsImage: image)
                .resizable()
                .interpolation(.high)
                .aspectRatio(contentMode: .fit)
        } else {
            Image(systemName: "chevron.left.forwardslash.chevron.right")
                .resizable()
                .aspectRatio(contentMode: .fit)
        }
    }
}
